### ISSUE TITLE
TODO for JSR 292 MethodHandleNatives APIs

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse/openj9#11443]
- [ ] Add impl for `Java_java_lang_invoke_MethodHandleNatives_getNamedCon` to support Java assertion
- [ ] use `registerNatives` for function export rather than uma and cmake export
- [ ] add support for HCR update for `J9JNIFieldID/J9JNIMethodID` pointers in MemberName object
