### ISSUE TITLE
Valhalla LWVT: Add support for Valhalla L-World value types

### ISSUE THREAD

**Issue by eric98zhang** [eclipse/openj9#1386]
Proposal: http://cr.openjdk.java.net/~acorn/LWorldValueTypesFeb13.pdf  
Unofficial spec: http://cr.openjdk.java.net/~fparain/L-world/L-World-JVMS-4b.pdf

- [x] Flatten value type instance fields #1387
- [ ] Flatten value type static fields #1388
- [ ] Flatten value type arrays #1389
- [x] Add new bytecodes #1390
- [ ] Update existing bytecodes #1391
- [ ] Update verifier checks #1392
- [ ] Performance testing #1393
- [ ] Update Java API (`Class.isValue()`) #1394
- [ ] Valhalla LWVT: Optimize value types #1503

---

L-World introduces _value class types_, distinct from _object class types_, _array types_ and _interface types_. These four types are considered to be _reference types_, and are all represented using the existing `LFoo;` signature.

Value types are identity-less and shallowly immutable, which allows for optimisations such as flattening of value type arrays and value type fields. 

**caveat**: The issues in this series were authored against the L-World specification. Some aspects may not be up-to-date wrt LW1.

**Comment by eric98zhang** [comment]
I just realised, there's no issue regarding the representation of value types themselves. e.g. things like new flags being added and changes to classfile reading.

**Comment by eric98zhang** [comment]
@tajila The issues look up-to-date to me. I will leave LW0/LW1 changes for you or Ali.
