### ISSUE TITLE
Enable DDR support for AIX

### ISSUE THREAD

**Issue by mikezhang1234567890** [eclipse/openj9#1769]
Ties into #378 

There is work needed in OpenJ9 and [eclipse/omr](https://github.com/eclipse/omr) order to bring up DDR on AIX 7.1 and up. Broadly, this work will consist of:

- [x] Changing makefiles in order to add the debug flags necessary for DDR on AIX and account for platform differences when building DDR on AIX

- [x] Fixing any issues with compiling the DDR code on AIX

- [x] DDR relies on libdwarf, however, AIX does not seem to have a supported library, and OMR's DDR does not use it. Instead OMR has its own parser. This parser needs to be fixed or replaced with libdwarf if we can compile it on AIX.

- [ ] Enable DDR by default in the extensions repos.
ibmruntimes/openj9-openjdk-jdk8#223
ibmruntimes/openj9-openjdk-jdk11#76
ibmruntimes/openj9-openjdk-jdk#59

- [ ] Enabling `-g` causes the AIX stackframe to be too large.  Need an alternative approach to ensure good perf with DDR enabled. See #3248. Fixed by #3995

- [ ] Enable DDR tests on AIX #3995

**Comment by pshipton** [comment]
Reverting DDR on AIX due to https://github.com/eclipse/openj9/issues/3248. Reopening this issue and assigning to the next milestone.
