### ISSUE TITLE
Correctly truncate boolean values in the appropriate bytecodes

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#2049]
Bytecodes that need to be updated:   **Complete in 0.11.0**
- [x]  bastore #2910 #2046
- [x] putfield / putstatic #2057 #2285
- [x] returns #1831 #1943

Targeted for 0.12.0:
- [x] Confirm whether JNI follows the same rules
- [x] VM truncate boolean JNI returns: ~~#3678~~ replaced by #3896
- [x] VM Truncate boolean writes in JNI and Unsafe: ~~#3648~~ replaced by #3896
- [x] VM Truncate boolean reads in Unsafe to match RI: #4045
- [x] JIT JNI directToJNI truncate boolean returns on X: #4086
- [x] All JIT Power work: https://github.com/eclipse/openj9/issues/4241
- [x] JNI truncation on Z: https://github.com/eclipse/openj9/issues/4162
- [x] JIT common work:  done in 0.11

- [x] JIT Unsafe truncate boolean writes in JNI / Unsafe to match #4045 & #3896 - jit implementation #6095

### Unsafe / JNI behaviour
As validated in #3896, JNI & Unsafe are checking ` != 0`, not `& 1`

### Check for boolean array when running bastore bytecode:

The JVM spec states: "If the arrayref refers to an array whose
components are of type boolean, then the int value is narrowed by taking
the bitwise AND of value and 1; the result is stored as the component of
the array indexed by index"

### Check for boolean array when running put{field,static} bytecodes:

The JVM spec states "If the value is of type int and the field
descriptor type is boolean, then the int value is narrowed by taking the
bitwise AND of value and 1, resulting in value'"

**Comment by DanHeidinga** [comment]
Opened an issue to connect the VM and JIT PRs for this issue.

**Comment by DanHeidinga** [comment]
@andrewcraik @fjeremic - I'll hold off merging the VM PR until we have an idea of when the JIT side can be ready

**Comment by fjeremic** [comment]
@DanHeidinga do we have a failing test case or unit tests for this one? @andrewcraik sounds like we need to change for from:

```
bstorei
  x
  y
```

to

```
bstorei
  x
  band
    y
    bconst 1
```

**Comment by fjeremic** [comment]
> I'll hold off merging the VM PR until we have an idea of when the JIT side can be ready

I have a fix ready in https://github.com/eclipse/openj9/pull/2055. Awaiting review.

**Comment by DanHeidinga** [comment]
See https://github.com/eclipse/openj9/pull/2046#issuecomment-393987313 for details on how to address `bastore` correctly in the JIT.

**Comment by gacholio** [comment]
What about JNI and Unsafe?

**Comment by jdmpapin** [comment]
Should `putfield` and `putstatic` (or at least some combination of those with a later `getfield`/`getstatic`) also truncate `byte`, `short`, and `char` values? It seems strange for them to truncate `boolean` only.

**Comment by gacholio** [comment]
I think Oracle uses correctly-sized fields in their object model, so it's a non-issue for them (the store is naturally truncated).  We never have a field smaller than int, so we probably should do the narrowing.

**Comment by tajila** [comment]
Just mentioning  https://github.com/eclipse/openj9/pull/1831 (https://github.com/eclipse/openj9/issues/999) as its related.

**Comment by fjeremic** [comment]
> @DanHeidinga @fjeremic @andrewcraik this issue is currently in the Release 0.10.0 milestone, will it be ready in this time frame (in the next couple of weeks)? If not, where should this be targeted? The 0.11.0 release will be for end of Oct, and 0.12.0 for Jan.

I believe @cathyzhyi is working on this. @cathyzhyi do we have an outlook for this work?

**Comment by cathyzhyi** [comment]
for JIT part, the putfield and putstatic is done. bastore needs more work. I am tied up with field watch stuff at this moment. Would start working on this in the next 2 weeks. The 0.11.0 release should work.

**Comment by pshipton** [comment]
Moving to the 0.11.0 milestone.

**Comment by ddoliver** [comment]
@pshipton is this complete?

**Comment by pshipton** [comment]
@ddoliver it is not complete, otherwise it would be closed. If you view it with ZenHub you can see the three related unmerged pull requests.

**Comment by DanHeidinga** [comment]
These items still need to be completed in 0.12.0:
> JIT JNI directToJNI truncate boolean returns: ???

And this will investigated for 0.13.0:
> JIT Unsafe truncate boolean writes in JNI / Unsafe

@andrewcraik can you comment on when the directToJNI change will be complete?

**Comment by hzongaro** [comment]
@DanHeidinga I'm looking at the directToJNI change for the JIT.  However, I'm unclear what the conclusion is about the desired behaviour.

I see that in the [comment above](https://github.com/eclipse/openj9/issues/2049#issue-328535791) and in pull request #3896, it's noted that the RI uses `!= 0` for the result of a `bool` JNI function.  However, this earlier [comment in pull request #3678](https://github.com/eclipse/openj9/pull/3678#issuecomment-440414568) states that "the preferred approach is to have the JIT update the code generated for the directToJNI case to include the `& 1`".

I just wanted to confirm that the `!= 0` is what we want.

**cc:** @andrewcraik

**Comment by tajila** [comment]
@hzongaro Previously we incorrectly assumed that JNI truncation would be the same as the bytecode truncation. The correct behaviour for JNI boolean returns is `!= 0`. We made this change in https://github.com/eclipse/openj9/pull/3896

**Comment by hzongaro** [comment]
Thanks for confirming, @tajila - I think that behaviour makes sense for JNI, given C/C++ semantics.

**Comment by DanHeidinga** [comment]
Moving the remaining work (JIT truncation in Unsafe) to 0.13.0.  All the 0.12.0 work is complete

**Comment by gita-omr** [comment]
@DanHeidinga do we have any test cases for this feature?

**Comment by gita-omr** [comment]
https://github.com/eclipse/openj9/issues/4241 is still in progress. What about Z? @fjeremic

**Comment by gita-omr** [comment]
@cathyzhyi, with the latest source I can see that we do &1 when storing to boolean static. Should we do !=1 ?

**Comment by DanHeidinga** [comment]
>  do we have any test cases for this feature?

@tajila is opening a PR with his tests.  He'll add a link here.

**Comment by gita-omr** [comment]
@R-santhir is looking at it on the Power side.

**Comment by tajila** [comment]
Link to boolean tests PR https://github.com/eclipse/openj9/pull/4274/

**Comment by gacholio** [comment]
Correct - we mask internally for java types, but use `!=0` for consistency with C for JNI.

**Comment by gita-omr** [comment]
Yes, I checked only putstatic and I could see VM doing !=0 and JIT IlGen doing &=1

**Comment by gacholio** [comment]
Wrong - putstatic (and putfield) does `&= 1`, JNI does '!= 0`

**Comment by pshipton** [comment]
@DanHeidinga can this be closed, or moved out of 0.13?

**Comment by DanHeidinga** [comment]
@fjeremic @gita-omr @andrewcraik can you confirm that the JIT work on your respective platforms is complete?

**Comment by fjeremic** [comment]
> @fjeremic @gita-omr @andrewcraik can you confirm that the JIT work on your respective platforms is complete?

Confirmed complete on Z.

**Comment by gita-omr** [comment]
Confirm that Power is done (as marked in the description).

**Comment by DanHeidinga** [comment]
@andrewcraik Can you confirm the JIT work on X is complete?  I believe it is based on the checkmarks above but confirmation would be good.

**Comment by DanHeidinga** [comment]
@andrewcraik confirmed this via slack

**Comment by pshipton** [comment]
@DanHeidinga does this need to be moved to the 0.15 milestone?

**Comment by DanHeidinga** [comment]
I've moved the last piece of work in this to 0.15.0 which is for the JIT to match the Unsafe changes:
*  JIT Unsafe truncate boolean writes in JNI / Unsafe to match #4045 & #3896

FYI @fjeremic @gita-omr @andrewcraik

**Comment by andrewcraik** [comment]
This can be done in the common code - @liqunl can you do the change - should be a small couple of lines.

**Comment by vij-singh** [comment]
@liqunl How is this one coming along?

**Comment by liqunl** [comment]
@vij-singh Sorry, I got sidetracked and forgot about this item. Let me check what I need to do.

**Comment by DanHeidinga** [comment]
With the merging of #6095, this is complete.
