### ISSUE TITLE
Concurrent Scavenge support on X86

### ISSUE THREAD

**Issue by 0dvictor** [eclipse/openj9#3054]
Concurrent Scavenge has proved a success on Z and hence X86 will follow. https://github.com/eclipse/omr/issues/2812 provides a good place naturally insert Concurrent Scavenge related read barriers. X86's implementation will take advantage of this new infrastructure and follow the overall principles from Z.

List of works:

- [x] GC to enable Concurrent Scavenge on X86 when `-Xgc:concurrentScavenge` is given; #3070
- [x] Optimizer to insert read barrier where necessary; #3074
- [x] CodeGen to evaluate read barrier correctly and to generate optimal instruction sequences; #3075
- [x] CodeGen to update reference arraycopy inlining sequence to call read barrier when necessary; #2963
- [x] GodeGen to update atomic compare and swap object inlining sequence to include a read barrier; #3111
- [x] Fix for J9VMJAVAUTILCONCURRENTLOCKSABSTRACTOWNABLESYNCHRONIZER; #3256
- [x] Turn on Concurrent Scavenge in the default Linux X86-64 CompressedRefs build spec; #3253

Documentation: https://github.com/eclipse/openj9-docs/issues/99

**Comment by dsouzai** [comment]
If X86 has any TM related instructions, you'll likely have to deal with those too.

**Comment by 0dvictor** [comment]
@vijaysun-omr FYI.

**Comment by andrewcraik** [comment]
created https://github.com/eclipse/openj9-docs/issues/99 as the docs issue.

**Comment by 0dvictor** [comment]
All pull requests listed in this Issue have been merger, closing.
