### ISSUE TITLE
Use NASM Assembler across all x86 operating systems

### ISSUE THREAD

**Issue by nbhuiyan** [eclipse/openj9#3148]
During the effort to port the OpenJ9 JIT on macOS, it became necessary to re-write the x86 assembly files in NASM format. Discussions around this topic occurred in #2418 

One of the main advantages of using NASM is that it is supported on all x86 platforms, meaning a unified assembler solution can be used throughout x86, consuming the same source files without requiring intermediate conversions. While the current assembly files are set up to work on macOS (see #2864), they are not set up to be used on xLinux and Windows yet. This issue will be used for tracking the work around enabling use of NASM across all x86 operating systems.

### The transition period

To enable macOS support, the NASM assembly files currently coexist with the MASM files that are used on Windows and Linux (after being processed by `masm2gas.pl`). This dual implementation will have to exist until support is added for Linux and Windows, which is expected to be completed within October 2018. In the meantime, any changes to the MASM files will have to be synced with the NASM files, and I will ensure that they remain synced. Here are the list of files that will need to be synced with their NASM versions, and will be removed once the migration is complete:

In [`runtime/compiler/x/runtime`](https://github.com/eclipse/openj9/tree/master/runtime/compiler/x/runtime)
* X86ArrayTranslate.asm
* X86Codert.asm
* X86EncodeUTF16.asm
* X86LockReservation.asm
* X86PicBuilder.inc
* X86PicBuilder.pasm
* X86RegisterMap.inc
* X86Unresolveds.pasm

In [`runtime/compiler/x/amd64/runtime`](https://github.com/eclipse/openj9/tree/master/runtime/compiler/x/amd64/runtime)
* AMD64CompressString.asm
* AMD64CompressString.inc
* AMD64Recompilation.asm

In [`runtime/compiler/x/i386/runtime`](https://github.com/eclipse/openj9/tree/master/runtime/compiler/x/i386/runtime)
* IA32CompressString.inc
* IA32Math64.inc
* IA32Recompilation.asm
* J9IA32CompressString.asm
* J9IA32Math64.asm

After the migration is complete, all new changes should be made in the NASM files. Syntactically, MASM and NASM are quite similar. There is an excellent [quick-start guide for MASM developers to migrate to NASM](https://www.nasm.us/doc/nasmdoc2.html#section-2.2) that highlights some of the major differences.

### List of tasks to complete migration

- [x] OSX Support (#2864)
- [x] Linux on x86-64 support (#3293)
- [x] Linux on x86 support (#4326)
- [x] Windows on x86-64 support (#3459)
- [x] Windows on x86 support (#4326)
- [x] Ensure nasm is set up and used in all xLinux and Windows CI/build environments (#2841 , #3352 , #3461 , #3493 )
- [ ] Clean up deprecated code resulting from this migration (#4627)
