### ISSUE TITLE
Make SVM generate few enough records to enable it during startup

### ISSUE THREAD

**Issue by jdmpapin** [eclipse/openj9#3752]
The symbol validation manager (SVM), introduced in #2919 and eclipse/omr#2978, allows ahead of time (AOT) compilations to inspect more run-time state than they were previously allowed to, and more completely captures the conditions (conservatively) required in order to load and run the generated code. As a result, it generates more validation records than the previous approach did—the total number of records generated, including (non-validation) relocations, can be up to 3× the prior count. Because the increase is so large, it is liable to regress startup time by exhausting the available space for AOT-compiled code, significantly reducing the number of methods loaded. As such, the SVM has been disabled during startup (394655f4) from the outset.

I have implemented a series of changes to the SVM, consisting first of cleanup (factoring duplicated code, deleting unused code, improving the assertions, etc.), followed by improvements that reduce the number of generated records. All told, these changes bring the number of records down by 33-50% to approximately 1.5× the original amount, which is hopefully low enough to prevent the SVM from causing a startup regression (although that will depend on the specific workload in question). There are quite a few changes, and this issue is to track them. Below I've included a rough dependency graph of my planned pull requests, which I will update as necessary to respond to merges and any requested changes (or just to fix errors, e.g. to add dependencies that I've missed). Many of the dependencies are incidental, due to the fact that the code must be changed in some particular order.

- [x] (a) Validate class chain for defining class of static (#3706)
- [x] (b) Delete code for unused validation kinds (#3977)
- [x] (c) Add `SVM_ASSERT*` macros, allowing assertions to be made fatal (#4007)
- [x] (4) Fix MethodFromClassAndSigRecord parameter order (#4075)
- [x] (3) Use regular getClassClassPointer() when using SVM (#4077)
- [x] (v) Lazily initialize class pointers on Compilation (#4111)
- [x] (d) Extract defineGuaranteedID() method in SVM (#4072)
- [x] (e) Check that symbol <-> ID lookups succeed (#4074)
- [x] (f) Store the SVM ID to symbol mapping as a vector (#4110)
- [x] (g) Track and check types for SVM symbol IDs (#4164)
- [x] (h) Add symbols of guaranteed IDs to _seenSymbolsSet (#4170)
- [x] (i) Define a guaranteed ID for null in the SVM, allowing optional fields (#4172)
- [x] (k) Replace MethodByName with SystemClassByName+MethodFromClassAndSig (#4175)
- [x] (L) omr: Remove callingMethod from getMethodFromName() (eclipse/omr#3562)
- [x] (m) Remove callingMethod from getMethodFromName() (#4735)
- [x] (5) Remove semicolon from SVM_ASSERT_ALREADY_VALIDATED (#4180)
- [x] (n) Cache repeatedly fetched values in SVM (#4178)
- [x] (o) Clarity: replace storeValidationRecordIfNecessary (#4181)
- [x] (p) Use a set in recordExists (#4259)
- [x] (q) Stop emitting SVM records for primitive arrays (#4491)
- [x] (r) Make SVM ArrayClassFromComponentClass bidirectional (#4506)
- [x] (s) Generate ProfiledClassRecord for new classes only (#4226)
- [x] (t) Use class chains for by-name class records (#4483)
- [x] (u) Create fewer ClassInstanceOfClass records (#4260)
- [x] (w) Fold ClassFromMethod into method records (#4529)
- [x] (x) Share common classes' class chain offset storage (#4666)
- [x] (y) Eliminate redundant ClassFromCP/ClassByName records (#4694)
- [x] (z) Avoid unnecessary SVM records for field references (#4695)

![](https://github.com/jdmpapin/svm-startup-deps/raw/master/svm-startup-deps.png)

Grey filled nodes have open pull requests. The dashed edges are only an ordering preference, not a real dependency.

**Comment by jdmpapin** [comment]
@andrewcraik @dsouzai @mstoodle FYI

**Comment by andrewcraik** [comment]
@jdmpapin thank you for taking on this big chunk of work - it certainly looks like it will be a great improvement to the AOT framework. I know that @dsouzai is working with some of the test folks to see if we can get a test bucket for AOT sorted so we can use that to test the pull requests (which is why I'm holding off on merging a just now until that discussion resolves).

**Comment by dsouzai** [comment]
I've opened https://github.com/eclipse/openj9/issues/3774 to track improving the AOT infrastructure. Adding new modes looks to be an ongoing process. However, at the very least, I will address the "Update Shared Classes Test to run twice" issue which will, at the very least, improve the AOT testing of the existing Shared Classes test found in the `systemTest` bucket.

**Comment by dsouzai** [comment]
https://github.com/eclipse/openj9-systemtest/pull/54 is merged, running the SCC tests in the systemTest bucket will result in two runs before destroying the SCC.

**Comment by fjeremic** [comment]
FYI if you use ZenHub you don't need the graph of dependencies since it supports issue dependency chains out of the box.

**Comment by jdmpapin** [comment]
#4723 has been merged
