### ISSUE TITLE
JEP 334 Constants API pr tracking

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9#4195]
Prerequisites (merge in order):
- [x] Make Java 12 compile: https://github.com/eclipse/openj9/pull/3980 (issues #3768 #4158)
- [x] Stubs for JEP: https://github.com/eclipse/openj9/pull/4030 
- [x] Java 12 test compile: https://github.com/eclipse/openj9/pull/4531
- [x] Java12AndUp test framework: https://github.com/eclipse/openj9/pull/4104 (moved to #4105 )

New methods for constants api:
- [x] String methods: https://github.com/eclipse/openj9/pull/4105 
- [x] Class methods: https://github.com/eclipse/openj9/pull/4157
- [x] MethodType methods (depends on Class pr): https://github.com/eclipse/openj9/pull/4194 
- [x] MethodHandle methods (depends on Class and MethodType prs): https://github.com/eclipse/openj9/pull/4412
- [x] VarHandle and VarHandleDesc methods (depends on Class pr): https://github.com/eclipse/openj9/pull/4449

**Comment by theresa-m** [comment]
all prs have been merged
