### ISSUE TITLE
All JIT Power work for "Improvements for Relocatable Compilations #2921"

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9#4242]
Power work for https://github.com/eclipse/openj9/issues/2921

**Comment by gita-omr** [comment]
Discussed with @aviansie-ben, @zl-wang and @vijaysun-omr : code is functionally stable, no known issues, but still more testing and performance tuning needs to be done.

**Comment by aviansie-ben** [comment]
I've started opening PRs to get this functionality merged. The PRs that need to be merged before this can be considered complete are:

- [ ] OpenJ9: Add support for SVM relocations to Power AheadOfTimeCompile
- [ ] OpenJ9: Fix improper J9Class materialization during IL generation (#4729)
- [ ] OpenJ9: Disable callerClassLoader optimization under AOT (#4727)
- [ ] OMR: Fix check for whether wide relocation offsets are needed on Power (eclipse/omr#3567)
- [ ] OMR: Add Power-specific relocation types needed for SVM AOT (eclipse/omr#3566)
- [ ] OpenJ9: Add Power-specific relocation types needed for SVM AOT
- [ ] OMR: Add support for generating SVM relocations under AOT
- [ ] OpenJ9: Add support for generating SVM relocations under AOT
- [ ] OpenJ9: Enable SVM by default on Power

**Comment by gita-omr** [comment]
@aviansie-ben is pretty much on track for enabling this in 0.13 so moving back to 0.13.

**Comment by aviansie-ben** [comment]
The last PR for this work has been merged, so this issue can be closed now.
