### ISSUE TITLE
Port JITServer to Z

### ISSUE THREAD

**Issue by dchopra001** [eclipse/openj9#6914]
I have a collection of fixes that will add JITServer support on the Z platform. This issue is to track the progress of getting all the fixes merged.

In order to get the changes merged, I have separated the patches into small commits. I will be opening Pull Requests to get these patches merged. In order to keep the discussions/concerns around every fix separate, I will open separate pull requests for each of the fixes.

Below is the list of PRs I have opened so far:

**JITServer branch**
- [x]  Add JITServer Dockerfiles for zLinux: https://github.com/eclipse/openj9/pull/6885
- [x]  Use front-end query to get ROMMethod from RAMMethod: https://github.com/eclipse/openj9/pull/6906
- [x]  Thunk related fixes: https://github.com/eclipse/openj9/pull/6907
- [x]  Create correct relocation record for java_lang_invoke_ComputedCalls_dispatchJ9Method in remote compilations: https://github.com/eclipse/openj9/pull/6908
- [x]  Use front-end implementation of the instanceOfOrCheckCast routines: https://github.com/eclipse/openj9/pull/6909
- [x]  Get existing method info from the J9Method instead of startPC: https://github.com/eclipse/openj9/pull/6912
- [x]  Add assert inside getjittedBodyInfoFromPC: https://github.com/eclipse/openj9/pull/6913
- [x] Add JITServer checks in the z codegen, as well as make an includes fix: https://github.com/eclipse/openj9/pull/6921
- [x] Don't add relo records for TR_MethodObject during remote compilations: https://github.com/eclipse/openj9/pull/6924
- [x] Disable ArrayTranslateAndTest support on Z for remote compilations: https://github.com/eclipse/openj9/pull/6925
- [x] Disable countDigits idiom recognition for remote compilations: https://github.com/eclipse/openj9/pull/6926
- [x] Disable isVettedForAOT when getting systemClass: https://github.com/eclipse/openj9/pull/6928

**Master branch**
- [x]  Use correct front end query when allocating VI Thunks: https://github.com/eclipse/openj9/pull/6910
- [x] Don't access ROM class from RAM class directly: https://github.com/eclipse/openj9/pull/6922
- [x] Introduce TR_MethodCallAddress to the relocation header size table: https://github.com/eclipse/openj9/pull/6923
- [x] Don't try to inline AtomicLong methods if classBlock is null: https://github.com/eclipse/openj9/pull/6927
- [x] Use correct query when adding TR_DataAddress relo records: #6929
- [x]  Use correct query to get RAM Method for remote compilations: https://github.com/eclipse/openj9/pull/6911
- [x] Rename helpersNeedRelocation to needRelocationsForHelpers: https://github.com/eclipse/openj9/pull/7661
- [x] Properly handle runtime assumptions in S390J9CallDataSnippet: #9984
- [x] Disable array translate support for remote compilations: #10088
- [x] Refactor allowGuardMerging() to the common codegen: #10090
- [ ] Override OMR's supportsMergingGuards routine: #10112
- [x] Override canUseRelativeLongInstructions in Z codegen: #10113
- [x] Remove some statics from z/codegen: #9652
- [x] Properly handle runtime assumptions in S390J9CallDataSnippet: #9984
- [x] Get target JITServer's CPU before CG object is created: #10474
- [x] JITServer on Z build fixes: #10688, #10702

Indirect cleanup work needed in order to enable JITServer functionality:
- [x] Update APIs using S390JNICallDataSnippet in OpenJ9: #9667
- [x] Add S390JNICallDataSnippet class: #9693
- [x] Rename S390JNICallDataSnippet2 to S390JNICallDataSnippet: #9842
- [x] Handle new CPU enum types inside J9CPU.cpp: #10390

**Comment by dchopra001** [comment]
@mpirvu FYI. I'll need reviews from you for all the PRs above. I'm tagging you here so you are able see all the PRs in a single place.

**Comment by dchopra001** [comment]
JITServer should now be functional on Z. I have updated the final issue with build results here: https://github.com/eclipse/openj9/pull/10688#issuecomment-699039258. 

If any new issues arise in the future, then they can be solved individually. Closing this issue.
