### ISSUE TITLE
Port JITServer to Power

### ISSUE THREAD

**Issue by dchopra001** [eclipse/openj9#6991]
This issue will be used to track all the PRs I will be opening to implement JITServer support on Power. See #6914 for a similar issue for Z.

Below is the list of PRs:

**JITServer Branch** 
- [x] JITServer Compilation Fixes for Power: #6990
- [x] Direct call fixes for JITServer on Power: #7384
- [x] Disable use of TR_VMField on JITServer: #7385
- [x] Use JITServer check to create a relocation record for interface calls on Power: #7386
- [x] Disable JNI specialCasing of java_util_zip_CRC32_updateBytes: #7391
- [x] Add JITServer assert in getJITTedbodyInfoFromPC: #7392

**Master Branch**
- [x] Add TR_MethodCallAddress to the relo runtimes table on Power: https://github.com/eclipse/openj9/pull/7383
- [x] Enable reloLogging for JITServer: #7388
- [x] Use FE query to do instanceOfOrCheckcast check on Power: #7390
- [x] Use FE query to get ROM method from RAM method: #7393
- [x] Create relocatable code when inlining string hash code #7387 
- [x] Update loadAddressConstant call to generate relocatable code on JITServer: #7389
- [x] Override needRelocationsForLookupEvaluationData: #7793
- [x] Update consumers of loadAddressConstant API: #7796
- [x] Override CG query to decide when to emit data: #7815
- [x] Add new needRelocationsForCurrentMethodPC query: #7959
- [x] Disable TOC for Remote Compilations: #7958

**Comment by dchopra001** [comment]
@mpirvu FYI

**Comment by dchopra001** [comment]
@mpirvu I have updated the comment with all the changes I have on the OpenJ9 side. Except for the one item that's still WIP, everything else is ready for review.

@ymanton I got your help for many of the fixes here, and so it'll be good if you are able to review these PRs as well.

@gita-omr It'd be great if you are able to take a quick look as well as most of these changes are going into the power codegen.

**Comment by gita-omr** [comment]
I took a look at the master branch PRs and they LGTM. Thanks!

**Comment by dchopra001** [comment]
I have opened PRs in OMR to address all the JITServer related changes. 

Most of the PRs are open as drafts because they are using the `comp->isOutOfProcessCompilation()` query that is not a valid query in OMR. While doing the implementation I wasn't sure which front end query to use, so I proceeded with using `comp->isOutOfProcessCompilation()` in order to first achieve functional correctness. We can discuss and finalize in each of the PRs what the final queries should look like

Where it made sense, I have also divided each PR into separate commits and additional comments so as to provide more context about the changes being made.

The list of PRs is below:

- [ ] Remove isAOT check in order to enable relo logging for JITServer: #4445
- [ ] Add isRelocatable boolean to power's loadAddressConstant API: #4441
- [ ] Rework MemoryReference::accessStaticItem in Power for JITServer: #4442
- [ ] Disable TOC for JITServer: #4443
- [ ] Add JITServer checks in the Power codegen #4444

@mpirvu @ymanton @gita-omr FYI

**Comment by dchopra001** [comment]
Just a note: the two PRs remaining here depend on an OMR PR which hasn't been merged yet. It should be easy to push these through once that one has been merged.

**Comment by dchopra001** [comment]
A few of the PRs above need to be double delivered. I'm making a list of the new PRs here:

- [ ] Direct call fixes for JITServer on Power: #7801
- [ ] Disable use of TR_VMField on JITServer: #7802
- [ ] Use JITServer check to create a relocation record for interface calls on Power: #7803
- [ ] Disable JNI specialCasing of java_util_zip_CRC32_updateBytes: #7804

**Comment by mpirvu** [comment]
I think that the port on Power has finished, so this issue can be closed now.
@dchopra001 if I am mistaken, please reopen.
