### ISSUE TITLE
Missing audio-input entitlement on macos

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#9402]
See AdoptOpenJDK/openjdk-build#1720 - any adjustments to `entitlements.plist` will need to be reflected in our extension repos as well:
- [x] jdk8 - ibmruntimes/openj9-openjdk-jdk8#431
- [x] jdk11 - ibmruntimes/openj9-openjdk-jdk11#309
- [x] jdk14 - ibmruntimes/openj9-openjdk-jdk14#66
- [x] jdk15 - ibmruntimes/openj9-openjdk-jdk#208

**Comment by pshipton** [comment]
@keithc-ca https://github.com/AdoptOpenJDK/openjdk-build/issues/1720 is closed. Can the necessary changes be added to the extensions now?

**Comment by keithc-ca** [comment]
It doesn't look like the changes from openjdk have been absorbed into our repos (at least not for jdk11). Do we need to manually trigger a job to do that?

**Comment by pshipton** [comment]
> Do we need to manually trigger a job to do that?

No. Every time there is a new level we merge it and run the acceptance build. Last promotion of 11.0.8+4 was on May 22. We could wait a couple weeks for the next level and look again.

**Comment by pshipton** [comment]
Forgot to mention that 11.0.8+4 is the latest atm.
